name: Poisonfish
favicon: null
layout_spectrum: 0.16096
typography_spectrum: 0.24029
title: Poisonfish Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#491369'
    - '#a084b2'
    - '#dcd2e2'
    - '#62347c'
  brandStrength: 0.7982019672635943
  lightness: 0.32717793993651867
  saturation: 0.4847726193256676
  rhythmicContrast: 0.3250241316854954
purpose: []
